-- ============================================================
-- Seed: Maintenance Task Templates
-- 26 templates organized by season + monthly recurring tasks
-- No RLS needed — templates are read-only reference data
-- ============================================================

-- SPRING TASKS
INSERT INTO maintenance_task_templates (name, description, instructions, category, season, recurrence, default_month, difficulty, diy_or_pro, priority, estimated_minutes, tools_needed, supplies_needed, climate_zones) VALUES
  ('Service air conditioner', 'Annual AC tune-up before summer', 'Schedule professional HVAC service to inspect refrigerant levels, clean coils, check electrical connections, and test thermostat calibration.', 'hvac', 'spring', 'annual', 4, 'involved', 'professional', 'high', 60, '[]', '[]', '{2,3,4,5,6,7,8}'),
  ('Clean gutters and downspouts', 'Remove debris from winter and spring blooms', 'Remove leaves and debris from all gutters. Flush with hose to verify proper drainage. Check downspout extensions direct water away from foundation.', 'exterior', 'spring', 'biannual', 4, 'moderate', 'either', 'medium', 90, '["ladder", "garden hose", "gloves", "trowel"]', '["gutter sealant"]', NULL),
  ('Inspect roof for winter damage', 'Check for missing, cracked, or curling shingles', 'Use binoculars from ground or carefully climb ladder to inspect. Look for missing shingles, damaged flashing around vents/chimney, and signs of sagging.', 'exterior', 'spring', 'annual', 3, 'moderate', 'either', 'high', 30, '["binoculars", "ladder"]', '[]', NULL),
  ('Check exterior caulking and weatherstripping', 'Inspect and repair seals around windows and doors', 'Check caulking around all windows, doors, and exterior penetrations. Replace any cracked or missing caulk. Check weatherstripping on all doors.', 'exterior', 'spring', 'annual', 4, 'easy', 'diy', 'medium', 60, '["caulk gun"]', '["exterior caulk", "weatherstripping"]', NULL),
  ('Test and activate sprinkler system', 'Restart irrigation after winter', 'Slowly open main water valve. Run each zone manually and check for broken heads, leaks, and proper coverage. Adjust spray patterns as needed.', 'exterior', 'spring', 'annual', 4, 'easy', 'diy', 'medium', 45, '[]', '["replacement sprinkler heads"]', '{3,4,5,6,7,8}'),
  ('Power wash exterior surfaces', 'Clean siding, driveway, walkways, and deck', 'Power wash siding (appropriate pressure for material), concrete surfaces, and deck/patio. Check for any damage revealed after cleaning.', 'exterior', 'spring', 'annual', 5, 'moderate', 'either', 'low', 180, '["pressure washer"]', '["cleaning solution"]', NULL),

-- SUMMER TASKS
  ('Clean dryer vent and ductwork', 'Prevent fire hazard from lint buildup', 'Disconnect dryer vent from back of dryer. Use dryer vent brush to clean entire duct run to exterior. Clean lint trap housing. Verify exterior vent flap opens properly.', 'interior', 'summer', 'annual', 6, 'moderate', 'either', 'high', 45, '["dryer vent brush", "vacuum", "screwdriver"]', '[]', NULL),
  ('Inspect and stain/seal deck', 'Protect wood deck from weather damage', 'Inspect deck boards for rot, loose nails, or structural issues. Sand rough spots. Apply wood stain or sealant per product instructions.', 'exterior', 'summer', 'annual', 6, 'moderate', 'diy', 'medium', 240, '["sander", "paintbrush", "roller"]', '["deck stain or sealant"]', NULL),
  ('Check exterior paint for peeling', 'Maintain exterior finish and prevent rot', 'Walk around entire house looking for peeling, bubbling, or fading paint. Scrape loose paint, prime, and touch up as needed.', 'exterior', 'summer', 'annual', 7, 'moderate', 'diy', 'medium', 120, '["scraper", "paintbrush"]', '["primer", "exterior paint"]', NULL),
  ('Inspect garage door operation', 'Ensure safe and smooth operation', 'Test auto-reverse safety feature (place 2x4 under door). Lubricate rollers, hinges, and tracks. Check weatherstripping at bottom. Inspect springs for wear.', 'exterior', 'summer', 'annual', 7, 'easy', 'diy', 'medium', 30, '[]', '["garage door lubricant"]', NULL),
  ('Clean refrigerator condenser coils', 'Improve efficiency and extend lifespan', 'Pull refrigerator out, unplug it, and vacuum the condenser coils on the back or bottom. Remove dust and pet hair buildup.', 'interior', 'summer', 'biannual', 6, 'easy', 'diy', 'low', 20, '["vacuum with brush attachment"]', '[]', NULL),

-- FALL TASKS
  ('Service furnace / heating system', 'Annual heating tune-up before winter', 'Schedule professional HVAC service to inspect heat exchanger, clean burners, check gas connections, test safety controls, and replace filter.', 'hvac', 'fall', 'annual', 10, 'involved', 'professional', 'high', 60, '[]', '[]', '{2,3,4,5,6,7,8}'),
  ('Clean gutters and downspouts (fall)', 'Remove fallen leaves before winter', 'Thorough gutter cleaning after leaves have fallen. This is the most critical gutter cleaning of the year to prevent ice dams.', 'exterior', 'fall', 'annual', 11, 'moderate', 'either', 'high', 90, '["ladder", "garden hose", "gloves", "trowel"]', '["gutter sealant"]', NULL),
  ('Winterize sprinkler system', 'Blow out lines to prevent freeze damage', 'Shut off water supply to sprinkler system. Use air compressor to blow out all water from lines. Insulate above-ground pipes and backflow preventer.', 'exterior', 'fall', 'annual', 10, 'moderate', 'either', 'high', 60, '["air compressor"]', '["pipe insulation"]', '{4,5,6,7,8}'),
  ('Inspect and clean chimney', 'Remove creosote and check for damage', 'Schedule professional chimney sweep and inspection. Check flue for creosote buildup, cracks, and proper draft. Inspect chimney cap and crown.', 'interior', 'fall', 'annual', 10, 'involved', 'professional', 'high', 60, '[]', '[]', '{3,4,5,6,7,8}'),
  ('Test heating system before cold weather', 'Verify heat works before you need it', 'Turn on heating system and run for 30+ minutes. Check all vents for airflow. Listen for unusual sounds. Check for burning smells (normal briefly for first use).', 'hvac', 'fall', 'annual', 10, 'easy', 'diy', 'high', 15, '[]', '[]', '{3,4,5,6,7,8}'),
  ('Disconnect and drain outdoor hoses', 'Prevent frozen pipes and hose bibb damage', 'Disconnect all garden hoses. Drain water from hose bibbs. Install insulated covers on exterior faucets. Close interior shutoff valves to outdoor faucets if available.', 'exterior', 'fall', 'annual', 11, 'easy', 'diy', 'high', 20, '[]', '["hose bibb covers"]', '{4,5,6,7,8}'),

-- WINTER TASKS
  ('Check for ice dams', 'Prevent roof and water damage from ice buildup', 'After snowfall, check eaves for icicle formation and ice dams. If present, use roof rake to remove snow from first 3 feet of roof edge. Do NOT chip ice.', 'exterior', 'winter', 'monthly', 1, 'moderate', 'diy', 'high', 30, '["roof rake"]', '["ice melt (calcium chloride)"]', '{5,6,7,8}'),
  ('Inspect pipe insulation', 'Prevent frozen pipes during cold snaps', 'Check insulation on pipes in unheated areas: garage, crawlspace, attic, exterior walls. Add insulation where missing. Open cabinets under sinks on exterior walls during extreme cold.', 'interior', 'winter', 'annual', 12, 'easy', 'diy', 'high', 30, '[]', '["pipe insulation"]', '{4,5,6,7,8}'),
  ('Check for drafts around windows and doors', 'Reduce heating costs and improve comfort', 'On a windy day, hold a candle or incense near window and door frames. Seal any drafts with caulk or weatherstripping.', 'interior', 'winter', 'annual', 12, 'easy', 'diy', 'medium', 45, '["caulk gun"]', '["interior caulk", "weatherstripping"]', '{4,5,6,7,8}'),

-- MONTHLY TASKS (year-round)
  ('Replace HVAC filter', 'Maintain air quality and system efficiency', 'Check filter condition. Replace if dirty (most filters need replacement every 1-3 months). Write the date on the new filter with a marker.', 'hvac', NULL, 'monthly', NULL, 'easy', 'diy', 'high', 5, '[]', '["HVAC filter (check size)"]', NULL),
  ('Test smoke and CO detectors', 'Ensure life safety devices are working', 'Press test button on each smoke and carbon monoxide detector. Replace batteries if needed. Detectors older than 10 years should be replaced entirely.', 'interior', NULL, 'monthly', NULL, 'easy', 'diy', 'critical', 10, '[]', '["9V batteries"]', NULL),
  ('Run water in unused drains', 'Prevent sewer gas from entering home', 'Run water for 30 seconds in any sink, tub, or floor drain that has not been used in the past month. This refills the P-trap seal.', 'plumbing', NULL, 'monthly', NULL, 'easy', 'diy', 'low', 5, '[]', '[]', NULL),
  ('Clean garbage disposal', 'Remove buildup and odors', 'Run ice cubes through disposal to clean blades. Follow with lemon or orange peels for freshening. Alternatively, use baking soda and vinegar.', 'interior', NULL, 'monthly', NULL, 'easy', 'diy', 'low', 5, '[]', '["ice cubes", "citrus peels"]', NULL),

-- QUARTERLY TASKS
  ('Inspect water heater', 'Check for leaks, corrosion, and sediment buildup', 'Inspect anode rod condition. Flush sediment by attaching hose to drain valve and releasing 2 gallons. Check pressure relief valve. Inspect for corrosion around fittings.', 'plumbing', NULL, 'quarterly', NULL, 'moderate', 'either', 'medium', 30, '["garden hose"]', '[]', NULL),
  ('Check fire extinguishers', 'Verify extinguishers are charged and accessible', 'Check pressure gauge on all extinguishers — needle should be in green zone. Inspect for physical damage. Verify pin and tamper seal are intact. Check expiration date.', 'interior', NULL, 'annual', NULL, 'easy', 'diy', 'critical', 10, '[]', '[]', NULL);
